resources:
- name: pipeline-scripts
  type: git
  source:
    branch: master
    uri: {{git-project-url}}

jobs:
- name: PCF
  type: cf
  source:
    api: {{pcf-api}}
    organization: {{deploy-organization}}
    space: {{deploy-space}}
    username: {{deploy-username}}
    password: {{deploy-password}}
    skip_cert_check: true

- 
# sample cf push command for nats-to-syslog app-build-output
# cf push nats-to-syslog -c './nats_to_syslog_linux_amd64 -nats-uri nats://nats:<nats password>@<nats-ip>:4222 -nats-subject ">" -syslog-endpoint <syslog-server>:514' --no-route -b binary_buildpack --health-check-type none -m 256M
